version: "3"
services:
  books-db:
    image: postgres:12.3
    container_name: books-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=books
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/

