server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger

spring:
  application:
    name: books
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/books?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: books
    password: BOOKS_password
    hikari:
      schema: books_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS books_schema;
      connection-timeout: 10000

app:
  cache:
    cache-names:
      - booksByCategory
      - bookByTitleAndAuthor
    caches:
      booksByCategory:
        expiry: 10m
      bookByTitleAndAuthor:
        expiry: 10m

logging:
  level:
    org:
      springframework: INFO
      example:
        books: INFO
